const mongoose = require('mongoose');

const gameSchema = new mongoose.Schema({
  prompt: { type: String, required: true },
  config: { type: Object, required: true }, // The JSON generated by AI
  createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Game', gameSchema);
